

try { console.log(e) } catch(err) { if(err.includes('ReferenceError')) {console.log('Reference Error')} }{
  console.log}